-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.recipes
(
    created_at timestamp with time zone DEFAULT now(),
    name character varying COLLATE pg_catalog."default",
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    author uuid NOT NULL,
    CONSTRAINT recipes_pkey PRIMARY KEY (id),
    CONSTRAINT recipes_author_fkey FOREIGN KEY (author)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recipes
    OWNER to postgres;

ALTER TABLE IF EXISTS public.recipes
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.recipes TO anon;

GRANT ALL ON TABLE public.recipes TO authenticated;

GRANT ALL ON TABLE public.recipes TO postgres;

GRANT ALL ON TABLE public.recipes TO service_role;

GRANT ALL ON TABLE public.recipes TO supabase_admin;
