-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.ingredients DROP COLUMN IF EXISTS id;

ALTER TABLE IF EXISTS public.ingredients
    RENAME id TO created_at;

ALTER TABLE public.ingredients
    ALTER COLUMN created_at TYPE timestamp with time zone ;
ALTER TABLE IF EXISTS public.ingredients
    ALTER COLUMN created_at SET DEFAULT now();

ALTER TABLE IF EXISTS public.ingredients
    ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE IF EXISTS public.ingredients
    RENAME id TO name;

ALTER TABLE public.ingredients
    ALTER COLUMN name TYPE character varying COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public.ingredients
    ALTER COLUMN name DROP DEFAULT;

ALTER TABLE IF EXISTS public.ingredients
    ALTER COLUMN name SET STORAGE EXTENDED;
ALTER TABLE IF EXISTS public.ingredients
    ADD CONSTRAINT ingredients_pkey PRIMARY KEY (name);

ALTER TABLE IF EXISTS public.recipe_ingredients DROP COLUMN IF EXISTS ingredient_id;

ALTER TABLE IF EXISTS public.recipe_ingredients
    ADD COLUMN ingredient_name character varying COLLATE pg_catalog."default" NOT NULL;
ALTER TABLE IF EXISTS public.recipe_ingredients
    ADD CONSTRAINT recipe_ingredients_pkey PRIMARY KEY (recipe_id, ingredient_name);
ALTER TABLE IF EXISTS public.recipe_ingredients DROP CONSTRAINT IF EXISTS recipe_ingredients_ingredient_id_fkey;

ALTER TABLE IF EXISTS public.recipe_ingredients
    ADD CONSTRAINT recipe_ingredients_ingredient_name_fkey FOREIGN KEY (ingredient_name)
    REFERENCES public.ingredients (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
