-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.ingredients
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT ingredients_pkey PRIMARY KEY (id),
    CONSTRAINT ingredients_name_key UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.ingredients
    OWNER to postgres;

ALTER TABLE IF EXISTS public.ingredients
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.ingredients TO anon;

GRANT ALL ON TABLE public.ingredients TO authenticated;

GRANT ALL ON TABLE public.ingredients TO postgres;

GRANT ALL ON TABLE public.ingredients TO service_role;
CREATE POLICY "Enable all for authenticated users only"
    ON public.ingredients
    AS PERMISSIVE
    FOR ALL
    TO public
    USING ((auth.role() = 'authenticated'::text))
    WITH CHECK ((auth.role() = 'authenticated'::text));

CREATE TABLE IF NOT EXISTS public.recipe_ingredients
(
    recipe_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    ingredient_id uuid NOT NULL,
    unit character varying COLLATE pg_catalog."default" NOT NULL,
    quantity character varying COLLATE pg_catalog."default" NOT NULL,
    "order" smallint NOT NULL,
    CONSTRAINT recipe_ingredients_pkey PRIMARY KEY (recipe_id, ingredient_id),
    CONSTRAINT recipe_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id)
        REFERENCES public.ingredients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT recipe_ingredients_recipe_id_fkey FOREIGN KEY (recipe_id)
        REFERENCES public.recipes (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recipe_ingredients
    OWNER to postgres;

ALTER TABLE IF EXISTS public.recipe_ingredients
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.recipe_ingredients TO anon;

GRANT ALL ON TABLE public.recipe_ingredients TO authenticated;

GRANT ALL ON TABLE public.recipe_ingredients TO postgres;

GRANT ALL ON TABLE public.recipe_ingredients TO service_role;
CREATE POLICY "Enable all for users based on author"
    ON public.recipe_ingredients
    AS PERMISSIVE
    FOR ALL
    TO public
    USING ((auth.uid() IN ( SELECT recipes.author
   FROM recipes
  WHERE (recipe_ingredients.recipe_id = recipes.id))));

ALTER TABLE IF EXISTS public.recipes
    ADD COLUMN content text COLLATE pg_catalog."default" NOT NULL;

CREATE POLICY "Enable all for users based on author"
    ON public.recipes
    AS PERMISSIVE
    FOR ALL
    TO public
    USING ((auth.uid() = author));
